name: C/C++ CI
permissions:
  contents: write
  pages: write
  id-token: write
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: mymindstorm/setup-emsdk@v14
      - name: Verify
        run: emcc -v
      - uses: actions/checkout@v4
      - name: Make
        run: emmake make
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
             name: web_terminal
             path: ${{github.workspace}}/bin/ 
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4.0.5
    
          
        
      

      
